-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 18:36:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema entervista
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema entervista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `entervista` DEFAULT CHARACTER SET utf8mb4;
USE `entervista` ;

-- -----------------------------------------------------
-- Table `entervista`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`area` ;

CREATE TABLE IF NOT EXISTS `entervista`.`area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`candidato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`candidato` ;

CREATE TABLE IF NOT EXISTS `entervista`.`candidato` (
  `idCandidato` INT NOT NULL,
  `nombre` VARCHAR(90) NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `RG` VARCHAR(9) NOT NULL,
  `idArea` INT NOT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idCandidato`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC) VISIBLE,
  INDEX `fk_Candidato_Area_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `fk_Candidato_Area`
    FOREIGN KEY (`idArea`)
    REFERENCES `entervista`.`area` (`idArea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`perguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`perguntas` ;

CREATE TABLE IF NOT EXISTS `entervista`.`perguntas` (
  `idPeguntas` INT NOT NULL,
  `Perguntas` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idPeguntas`),
  UNIQUE INDEX `idPeguntas_UNIQUE` (`idPeguntas` ASC) VISIBLE,
  UNIQUE INDEX `Perguntas_UNIQUE` (`Perguntas` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`questionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`questionario` ;

CREATE TABLE IF NOT EXISTS `entervista`.`questionario` (
  `idQuestionario` INT NOT NULL,
  `idArea` INT NOT NULL,
  PRIMARY KEY (`idQuestionario`),
  INDEX `fk_questionario_area1_idx` (`idArea` ASC) VISIBLE,
  CONSTRAINT `fk_questionario_area1`
    FOREIGN KEY (`idArea`)
    REFERENCES `entervista`.`area` (`idArea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`questionariopergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`questionariopergunta` ;

CREATE TABLE IF NOT EXISTS `entervista`.`questionariopergunta` (
  `idQuestionarioPergunta` INT NOT NULL,
  `idPeguntas` INT NULL DEFAULT NULL,
  `idQuestionario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idQuestionarioPergunta`),
  INDEX `fk_perguntas_has_Questionario_Questionario1_idx` (`idQuestionario` ASC) VISIBLE,
  INDEX `fk_perguntas_has_Questionario_perguntas1_idx` (`idPeguntas` ASC) VISIBLE,
  CONSTRAINT `fk_perguntas_has_Questionario_perguntas1`
    FOREIGN KEY (`idPeguntas`)
    REFERENCES `entervista`.`perguntas` (`idPeguntas`),
  CONSTRAINT `fk_perguntas_has_Questionario_Questionario1`
    FOREIGN KEY (`idQuestionario`)
    REFERENCES `entervista`.`questionario` (`idQuestionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`entrevistador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`entrevistador` ;

CREATE TABLE IF NOT EXISTS `entervista`.`entrevistador` (
  `idEntrevistador` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `CPF` VARCHAR(11) NULL DEFAULT NULL,
  `RG` VARCHAR(9) NULL DEFAULT NULL,
  `dataNascimento` DATE NULL DEFAULT NULL,
  `matricula` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEntrevistador`),
  UNIQUE INDEX `Matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `RG_UNIQUE` (`RG` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`user` ;

CREATE TABLE IF NOT EXISTS `entervista`.`user` (
  `idUser` INT NOT NULL,
  `nombreDeUsuario` VARCHAR(16) NOT NULL,
  `contrasena` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(190) NULL DEFAULT NULL,
  `idEntrevistador` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE,
  UNIQUE INDEX `nombreDeUsuario_UNIQUE` (`nombreDeUsuario` ASC) VISIBLE,
  INDEX `fk_user_Entrevistador1_idx` (`idEntrevistador` ASC) VISIBLE,
  CONSTRAINT `fk_user_Entrevistador1`
    FOREIGN KEY (`idEntrevistador`)
    REFERENCES `entervista`.`entrevistador` (`idEntrevistador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `entervista`.`entrevista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entervista`.`entrevista` ;

CREATE TABLE IF NOT EXISTS `entervista`.`entrevista` (
  `idEntrevista` INT NOT NULL,
  `idUser` INT NULL DEFAULT NULL,
  `idCandidato` INT NULL DEFAULT NULL,
  `idArea` INT NULL DEFAULT NULL,
  `DataEntrevista` DATE NULL DEFAULT NULL,
  `IdQuestionarioPergunta` INT NOT NULL,
  PRIMARY KEY (`idEntrevista`),
  INDEX `fk_Entrevista_Candidato1_idx` (`idCandidato` ASC) VISIBLE,
  INDEX `fk_Entrevista_Area1_idx` (`idArea` ASC) VISIBLE,
  INDEX `fk_Entrevista_user1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_Entrevista_perguntas_has_Questionario1_idx` (`IdQuestionarioPergunta` ASC) VISIBLE,
  CONSTRAINT `fk_Entrevista_Area1`
    FOREIGN KEY (`idArea`)
    REFERENCES `entervista`.`area` (`idArea`),
  CONSTRAINT `fk_Entrevista_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `entervista`.`candidato` (`idCandidato`),
  CONSTRAINT `fk_Entrevista_perguntas_has_Questionario1`
    FOREIGN KEY (`IdQuestionarioPergunta`)
    REFERENCES `entervista`.`questionariopergunta` (`idQuestionarioPergunta`),
  CONSTRAINT `fk_Entrevista_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `entervista`.`user` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
